### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by Term1nal** [ajhager/engi#17]
Radeon HD3650
Intel i5 3470
Ubuntu 14.04

Botmark with ~56k sprites barely ebbing below 60FPS.

That's pretty neat........

Just wanted to say thanks for sharing! I hope this gets some more work, I'll definitely be tinkering with it :3

**Comment by ajhager** [comment]
Thanks! I am currently working on making things better. It always helps to know other people are interested.

**Comment by Term1nal** [comment]
Maybe I could throw throw some requests your way?

Abstracted tilemap object with texture atlasing and spritebatching (though seems you got sprite batching down already :D ). Also, support for borderless tilemapping/chunking/faux-infinite tile maps.

I was working on learning OpenGL a bit in order to get the tilemapping stuff done (coming from C#/XNA) and using a key/value map to hold the pointers to "chunks" of the map. ( map[uint64]*Chunk )

Using uint64 so that I can bitwise concatenate two 32bit integers for an x,y coordinate-id of a given chunk (not an individual tile, I thought chunks maybe could have their own coordinate space, and maintain world coordinate space as a double or just 64bit integer), and use that as the key to the pointer containing the chunk.

```
func Pair(x, y uint32) uint64 {
	pair := uint64(x)
	return pair<<32 | uint64(y)
}

func Unpair(val uint64) (uint32, uint32) {
	x := uint32(val >> 32)
	y := uint32(val & 0xFFFFFFFF)
	return x, y
}
```

**Comment by Term1nal** [comment]
Also, on my big rig:

i7 5930K
DDR4 2800MHz
EVGA GTX980 Superclocked

http://i.imgur.com/bXEx0E0.png
